name: 💡 Feature Request
description: Suggest a new feature or enhancement for the Ultimate SEO Analysis Tool
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! 💡
        
        We love hearing ideas from our community. Please provide as much detail as possible to help us understand your suggestion.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and discussions to make sure this feature hasn't been requested
          required: true
        - label: I have read the [project roadmap](https://github.com/yourusername/ultimate-seo-analyzer#-roadmap) and contributing guidelines
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Describe the problem you're trying to solve or the use case you have in mind.
        
        Example: "As a SEO professional, I need to analyze multiple websites simultaneously because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you envision this feature working.
        
        Include:
        - User interface changes (if applicable)
        - New command-line options
        - Expected behavior
        - Integration with existing features
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - SEO Analysis Enhancement
        - Performance Improvement
        - User Interface/Experience
        - Reporting and Visualization
        - API Integration
        - Command Line Interface
        - Documentation
        - Testing and Quality
        - Security
        - Other (please specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use of the tool
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Describe any alternative approaches you've considered or current workarounds you're using.

  - type: textarea
    id: examples
    attributes:
      label: Examples and Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Provide concrete examples:
        
        1. Example command: `python ultimate_seo_analyzer.py --new-feature`
        2. Expected output: ...
        3. Use case: When analyzing e-commerce sites, I would use this to...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or References
      description: Any mockups, screenshots, or references to similar features in other tools?
      placeholder: |
        If you have mockups, screenshots, or can reference similar features in other tools, please include them here.
        
        You can drag and drop images directly into this text area.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check any that apply to your feature request
      options:
        - label: This feature would require changes to the command-line interface
        - label: This feature would require new dependencies
        - label: This feature would require API integrations
        - label: This feature would affect report generation
        - label: This feature would require database/storage changes
        - label: This feature might have performance implications
        - label: This feature would require documentation updates

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor changes to existing code
        - Medium - New functionality but straightforward
        - Complex - Significant changes or new components
        - Very Complex - Major architectural changes
        - Not sure

  - type: textarea
    id: benefits
    attributes:
      label: Benefits and Impact
      description: What benefits would this feature provide to users?
      placeholder: |
        Describe the benefits:
        
        - Who would benefit from this feature?
        - How would it improve the user experience?
        - What impact would it have on SEO analysis workflows?
        - Would it help with specific SEO challenges?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature
        - label: I would be willing to provide feedback during development

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the feature request
      placeholder: |
        Add any other context:
        
        - Links to relevant resources
        - Industry standards or best practices
        - Related tools or features
        - Technical specifications
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/yourusername/ultimate-seo-analyzer/blob/main/CODE_OF_CONDUCT.md)
          required: true